### ISSUE TITLE
Basic site for gazettes.africa

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/gazettes-africa#1]
We need

* [x] homepage
* [x] in jurisdiction detail page, show list of years and months
* [x] in jurisdiction year page, show list of gazettes for that year

**Comment by longhotsummer** [comment]
Updated the master branch with production gazette info.

**Comment by longhotsummer** [comment]
@AliciadW:

Footer:

* "Gazettes.Africa is a project of [Laws.Africa](https://laws.africa)."
* contact email: info@laws.africa
* no Terms of Use/PP
*  drop the little `edit` link
* now newsletter, etc.
* keep the NPO details

**Comment by AliciadW** [comment]
Thanks @longhotsummer
